#!/bin/bash

LOCKDIR=/var/lock/maps
LOCK=$LOCKDIR/apply-changes

if [ -f $LOCK ]; then
    echo "Someone's already applying changes! Check /var/lock/maps/apply-changes"
    exit 1
fi
touch $LOCK

ERROR=false

for change in /army/changes/*;
do
    changename=`basename $change`
    if [ $changename = '*' ]; then
        break
    fi
    osm2pgsql --append --slim -d gis -C 1600 --number-processes 3 -e0-18 -o /army/dirty-tiles-$changename $change || continue && ERROR=true
    if [ ! -f /army/dirty-tiles ]; then
        mv /army/dirty-tiles-$changename /army/dirty-tiles
    else
        cat /army/dirty-tiles-$changename >> /army/dirty-tiles
        rm -f /army/dirty-tiles-$changename
    fi
    rm -f $change
done

rm $LOCK

$ERROR && echo "There were some errors"
