#!/bin/bash
VERBOSE=true
USR_NAME="tiler"
GEN_TILES_DIR="/army/mapnik-stylesheets"

log() { $VERBOSE && echo $1; }

error() { echo -e "Error: "$1; exit; }

log "Creating user..."
sudo -u postgres psql postgres -tAc "select 1 from pg_roles where rolname='$USR_NAME'" | grep -q 1 || sudo -u postgres createuser $USR_NAME || error "Could not create user"
sudo -u postgres psql postgres -tAc "alter user $USR_NAME with password '$MAPS_PASS'" || sudo -u postgres createuser $USR_NAME || error "Could not set password"

log "Creating database..."
sudo -u postgres psql -l | grep gis -q || sudo -u postgres createdb -E UTF8 -O $USR_NAME gis || error "Could not create database"

log "Setting up postgis..."
sudo -u postgres psql -f /usr/pgsql-9.3/share/contrib/postgis-2.1/postgis.sql -d gis || error "Could not set up postgis"

log "Granting ownership to $USR_NAME user..."
sudo -u postgres psql -d gis -c "ALTER TABLE geometry_columns OWNER TO $USR_NAME; ALTER TABLE spatial_ref_sys OWNER TO $USR_NAME;" || error "Could not grant ownership"

log "Setting up osm2pgsql dependencies..."
sudo -u postgres psql -f /usr/share/osm2pgsql/900913.sql -d gis || error "Could not install 900913.sql"

log "Downloading PBF file"
get-new-jersey /army/lastupdate || error "Could not get date of PBF"
wget -O /army/new-jersey-latest.osm.pbf http://download.geofabrik.de/north-america/us/new-jersey-latest.osm.pbf || error "Could not download PBF"

log "Importing data into database..."
sudo -u $USR_NAME osm2pgsql --slim -d gis -C 1000 --number-processes 3 /army/new-jersey-latest.osm.pbf || error "Could not import data"

log "Generating stylesheet"
cd $GEN_TILES_DIR
./get-coastlines.sh || error "Could not get coastlines"
./generate_xml.py --dbname gis --host 'localhost' --user $USR_NAME --port 5432 --password="$MAPS_PASS" || error "Could not create stylesheet"

log "Rendering tiles..."
./generate_tiles.py --bbox -74.4969 40.4349 -74.3913 40.5563 --output-dir /army/tiles/ --stylesheet osm.xml || error "Could not render tiles"

cd -

log "Success! Database initialized and tiles rendered!"
