#!/usr/bin/env python

import os
import os.path
import shutil
import smtplib
import subprocess
import urllib2
import xml.etree.ElementTree as ET
import xml.dom.minidom as MD
from email import Encoders
from email.MIMEBase import MIMEBase
from email.MIMEMultipart import MIMEMultipart
from email.MIMEText import MIMEText
from email.Utils import formatdate

import argparse

from osm.models import OSMChange
from osm.nominatim import name_to_polygon

# URL for latest NJ pbf
NJ_LATEST = ("http://download.geofabrik.de/"
             "north-america/us/new-jersey-latest.osm.pbf")

# Disk locations for latest and previous NJ pbf
NJ_LATEST_PBF = '/army/new-jersey-latest.osm.pbf'
NJ_OLD_PBF = '/army/new-jersey-old.osm.pbf'

# Diff and changes disk locations
DIFF = '/army/diff.osc'
CHANGES = '/army/changes'
PENDING = '/army/pending'

RUTGERS_BBOX = [-74.5343, 40.4164, -74.3520, 40.5673]

def print_ET(root):
    """Pretty print xml from ElementTree"""
    print MD.parseString(ET.tostring(root)).toprettyxml(),


def send_mail(changes, address):
    """Send email requesting maps approval."""
    msg = MIMEMultipart()
    msg['From'] = 'phantoon'
    msg['To'] = address
    msg['Date'] = formatdate(localtime=True)
    msg['Subject'] = "Changes for Rutgers maps need approval"
    msg.attach(MIMEText(
        "The attached files need approval, run "
        "'/usr/bin/commit-changes' on phantoon to allow or deny changes"))
    for change in changes:
        part = MIMEBase('text', 'xml')
        part.set_payload(open(change, "r").read())
        Encoders.encode_base64(part)
        part.add_header('Content-Disposition', 'attachment; filename="{0}"'.
                        format(os.path.basename(change)))
        msg.attach(part)
    smtp = smtplib.SMTP('localhost')
    smtp.sendmail('phantoon', address, msg.as_string())
    smtp.close()


def get_new_jersey(outfile, nj_latest):
    """Download latest version of New Jersey from geofabrik"""
    with open(outfile, 'w') as f:
        f.write(urllib2.urlopen(nj_latest).read())


def lowest_avail_id(directory):
    current_ids = set(
        [int(os.path.splitext(f)[0]) for f in os.listdir(directory)])

    lowest_id = 1
    while lowest_id in current_ids:
        lowest_id += 1

    return lowest_id


def lowest_avail_filename(directory):
    return os.path.join(directory, str(lowest_avail_id(directory)) + '.osc')


def get_rutgers():
    busch = name_to_polygon("Rutgers Busch Campus", bbox=RUTGERS_BBOX)
    livi = name_to_polygon("Rutgers Livingston Campus", bbox=RUTGERS_BBOX)
    college_ave = name_to_polygon("Rutgers University - New Brunswick",
                                  bbox=RUTGERS_BBOX)
    return [busch, livi, college_ave]


def intersects_any(bbox, rutgers):
    for campus in rutgers:
        if bbox.intersects(campus):
            return True
    return False


if __name__ == '__main__':

    parser = argparse.ArgumentParser(
        description='Create change files based on a bounding box')
    parser.add_argument('-u', '--nj-url',
                        default=NJ_LATEST,
                        help='Url to get pbf from')
    parser.add_argument('-l', '--nj-latest',
                        default=NJ_LATEST_PBF,
                        help='Location to save new pbf')
    parser.add_argument('-o', '--nj-old',
                        default=NJ_OLD_PBF,
                        help='Location of the old pbf')
    parser.add_argument('-d', '--diff',
                        default=DIFF,
                        help='Diff location')
    parser.add_argument('-c', '--changes',
                        default=CHANGES,
                        help='Changes directory')
    parser.add_argument('-p', '--pending',
                        default=PENDING,
                        help='Pending directory')
    parser.add_argument('-s', '--short-circuit',
                        action='store_true')
    parser.add_argument('-m', '--no-send-mail',
                        action='store_true',
                        help='Add to stop mail sending')
    args = parser.parse_args()

    if not args.short_circuit:
        # Command run for osmosis, this command takes the two
        # pbfs and creates a new xml file that is the difference
        # between the two
        osmosis_cmd = [
            'osmosis',
            '--read-pbf',
            'file={0}'.format(args.nj_latest),
            '--read-pbf',
            'file={0}'.format(args.nj_old),
            '--derive-change',
            '--simplify-change',
            '--sort',
            '--write-xml-change',
            'file={0}'.format(args.diff)
        ]

        print "Moving old New Jersey file"
        shutil.move(args.nj_latest, args.nj_old)

        print "Getting new New Jersey file"
        get_new_jersey(args.nj_latest, args.nj_url)

        print "Calling osmosis"
        subprocess.check_call(osmosis_cmd)

        print "Removing old NJ file"
        os.remove(args.nj_old)

    rutgers = get_rutgers()

    print "Parsing diff"
    changes = OSMChange.from_xml(
            ET.parse(args.diff),
            etree.iterparse(args.nj_latest),
            etree.iterparse(args.nj_old))

    apply_create = []
    apply_modify = []
    apply_delete = []

    ask_create = []
    ask_modify = []
    ask_delete = []

    split_changes = [
        (apply_create, ask_create, changes.create),
        (apply_modify, ask_modify, changes.modify),
        (apply_delete, ask_delete, changes.delete)
    ]

    for apply_change, ask_change, change in split_changes:
        for element in change:
            if intersects_any(element.get_bbox(), rutgers):
                ask_change.append(element)
            else:
                apply_change.append(element)

    apply_changes = OSMChange(apply_create, apply_modify, apply_delete)
    ask_changes = OSMChange(ask_create, ask_modify, ask_delete)

    print "Writing files"
    change_filename = lowest_avail_filename(args.changes)
    pending_filename = lowest_avail_filename(args.pending)
    with open(change_filename, 'w') as f:
        f.write(ET.tostring(apply_changes.to_xml()))
    with open(pending_filename, 'w') as f:
        f.write(ET.tostring(ask_changes.to_xml()))

    if not args.no_send_mail:
        print "Sending mail"
        send_mail([change_filename, pending_filename],
                  'mwr54@nbcs.rutgers.edu')
